### ISSUE TITLE
Remove the text from connection dialogue

### ISSUE THREAD

**Issue by darkchylde** [decentralised-dataexchange/aries-mobileagent-iOS#43]
Remove the current text "Allow to connect with you" from the connection dialogue which is shown on trying to connect to an organisation

![2021-01-25_14-24](https://user-images.githubusercontent.com/16397960/105683035-2f75c300-5f19-11eb-944b-34d1529fc9dc.png)

**Comment by lalc** [comment]
@darkchylde, Spoke to @rebink and we thought its safer to add the organisation name just under the logo. Ok?
