### ISSUE TITLE
After the credential is issued, the data wallet hangs after notification is received

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/aries-mobileagent-iOS#52]
https://user-images.githubusercontent.com/455274/106395271-a7ecf000-6401-11eb-8771-8c728f98c396.MP4

but it goes into a loop.

Video attached. 

How it happened:
1. Added 2 orgs
2. Issued credentials
3. Added to the wallet
4. deleted the org cards and data cards

1. added the same orgs again with the same QR code
2. Issued the creds
3. hangs. but if u kill and come back to notification, you can add it there.

**Comment by rebink** [comment]
@lalc fixed.
