### ISSUE TITLE
Default logo image doesn’t look correct 

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/aries-mobileagent-iOS#54]
Pls check and fix it so it’s not cur

**Comment by lalc** [comment]
![BF4108C1-F4D1-449A-8274-E07DD326B77C](https://user-images.githubusercontent.com/455274/106397027-b8a26380-640b-11eb-9efb-bb4aa835774b.png)

**Comment by rebink** [comment]
@lalc Can you provide an image with padding.

**Comment by lalc** [comment]
Have provided in slack. Please check if that works. Else pls ping me back
