### ISSUE TITLE
The previous data card disappeared after new app updates

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/aries-mobileagent-iOS#79]

**Comment by darkchylde** [comment]
@lalc Don't know iOS app update strategy. Basically this happens when local sqlite database (or wallet) in the mobile gets deleted. @rebink Could you check this ?

**Comment by rebink** [comment]
@lalc depends on the build, If you are using testflight build and you installed a new build from the app store. Then It will override the testflight build and vice-versa. If you haven't uninstalled the build please try to install testflight build again and check if the old data is showing there or not.
